import './globals.css'
import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import { Header } from '@/components/header/header'

const lato = Lato({ subsets: ['latin'], weight: ['900'] })

export const metadata: Metadata = {
  title: 'Weather',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={lato.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
